vim.lsp.enable("emmylua_ls")
vim.lsp.enable("kotlin_lsp")
vim.lsp.enable("yamlls")
vim.lsp.enable("helm_ls")
vim.lsp.enable("marksman")
vim.lsp.enable("gradle_ls")
vim.lsp.enable("golangci_lint_ls")
vim.lsp.enable("clangd")
vim.lsp.enable("cmake")
-- NO SCALA HERE. I'm doing that with nvim-metals.
