vim.lsp.enable("beancount")
vim.lsp.enable("clangd")
vim.lsp.enable("emmylua_ls")
vim.lsp.enable("gleam")
vim.lsp.enable("golangci_lint_ls")
vim.lsp.enable("gradle_ls")
vim.lsp.enable("helm_ls")
vim.lsp.enable("kotlin_lsp")
vim.lsp.enable("marksman")
vim.lsp.enable("neocmake")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("yamlls")
-- NO SCALA HERE. I'm doing that with nvim-metals.
